batch_size: 24
dataset:
  type: pascal
  train:
    root_dir: /scratch/tmp/d_beck26/PascalVOC2012/VOC2012/focused_gaze/train
    use_embeddings: true
    prompt_types:
      - masks
    mask_type: gaze
  val:
    root_dir: /scratch/tmp/d_beck26/PascalVOC2012/VOC2012/focused_gaze/val
    use_embeddings: true
    prompt_types:
      - masks
    mask_type: gaze
eval_interval: 5
save_interval: 30
model:
  name: PrecomputedEmbeddingModel
  checkpoint: /home/d/d_beck26/lightning-sam/checkpoints/sam_vit_h_4b8939.pth
  freeze:
    image_encoder: true
    mask_decoder: false
    prompt_encoder: false
  type: vit_h
num_devices: 4
num_epochs: 75
num_workers: 4
num_nodes: 1
opt:
  decay_factor: 10
  learning_rate: 0.00002
  steps:
  - 750
  - 2000
  warmup_steps: 30
  weight_decay: 0.1
out_dir: /scratch/tmp/d_beck26/sam_training/
