batch_size: 24
dataset:
  type: pascal
  train:
    root_dir: /home/daniel/data_cache/PascalVOC2012/VOC2012/focused_gaze/train
    use_embeddings: true
    prompt_types:
      - masks
  val:
    root_dir: /home/daniel/data_cache/PascalVOC2012/VOC2012/focused_gaze/val
    use_embeddings: true
    prompt_types:
      - masks
eval_interval: 5
save_interval: 60
model:
  name: PrecomputedEmbeddingModel
  checkpoint: checkpoints/sam_vit_h_4b8939.pth
  freeze:
    image_encoder: true
    mask_decoder: false
    prompt_encoder: false
  type: vit_h
num_devices: 2
num_epochs: 75
num_workers: 0
opt:
  decay_factor: 10
  learning_rate: 0.0008
  steps:
  - 1500
  - 4000
  warmup_steps: 30
  weight_decay: 0.1
out_dir: out/training
