batch_size: 12
dataset:
  type: coco
  train:
    annotation_file: /data/coco/annotations/instances_train2017.json
    root_dir: /data/coco/train2017
  val:
    annotation_file: /data/coco/annotations/instances_val2017.json
    root_dir: /data/coco/val2017
eval_interval: 2
model:
  checkpoint: checkpoints/sam_vit_h_4b8939.pth
  freeze:
    image_encoder: true
    mask_decoder: false
    prompt_encoder: true
  type: vit_h
num_devices: 2
num_epochs: 2
num_workers: 0
opt:
  decay_factor: 10
  learning_rate: 0.0008
  steps:
  - 60000
  - 86666
  warmup_steps: 250
  weight_decay: 0.0001
out_dir: out/training
