batch_size: 24
dataset:
  type: pascal_embedding_gaze
  train:
    root_dir: /home/daniel/data_cache/PascalVOC2012/VOC2012/focused_gaze/train
  val:
    root_dir: /home/daniel/data_cache/PascalVOC2012/VOC2012/focused_gaze/train
eval_interval: 5
save_interval: 20
model:
  name: PrecomputedEmbeddingGazeModel
  checkpoint: checkpoints/sam_vit_h_4b8939.pth
  freeze:
    image_encoder: true
    mask_decoder: false
    prompt_encoder: true
  type: vit_h
num_devices: 2
num_epochs: 120
num_workers: 5
opt:
  decay_factor: 10
  learning_rate: 0.0008
  steps:
  - 2000
  - 3000
  warmup_steps: 250
  weight_decay: 0.1
out_dir: out/training
