batch_size: 10
dataset:
  type: coco
  train:
    annotation_file: /scratch/tmp/d_beck26/coco/annotations/instances_train2017.json
    root_dir: /scratch/tmp/d_beck26/coco/images/train2017
  val:
    annotation_file: /scratch/tmp/d_beck26/coco/annotations/instances_val2017.json
    root_dir: /scratch/tmp/d_beck26/coco/images/val2017
eval_interval: 2
model:
  checkpoint: /home/d/d_beck26/lightning-sam/checkpoints/sam_vit_h_4b8939.pth
  freeze:
    image_encoder: true
    mask_decoder: false
    prompt_encoder: true
  type: vit_h
num_devices: 4
num_epochs: 25
num_workers: 2
opt:
  decay_factor: 10
  learning_rate: 0.0008
  steps:
  - 60000
  - 86666
  warmup_steps: 250
  weight_decay: 0.0001
out_dir: /scratch/tmp/d_beck26/sam_training/
